### PR TITLE
added icons and team external link redirect option

### PR DESCRIPTION
**Pull request by julia-elias**

### CODE REVIEW

**Comment by luukee** [comment]
@julia-elias For some odd reason testing on your branch I found that some of the team members show the icons under their image and some dont. Very peculiar.

**Comment by julia-elias** [comment]
@luukee Thank you for letting me know! That is odd, but I'll make sure to look into it. I only have the icons display if the name, email, or link fields were filled out, but I don't know if that's the issue. Do you happen to remember which team members didn't have the icons displayed? No worries if not, I can look at the team members on the local site to see any issues.

**Comment by luukee** [comment]
@julia-elias Thanks for looking at it again for me. I still can't get my info to show up! (not that I really care ;) but we want this to be a solid fix. I even deleted my profile and re-added it. Very peculiar.

Screen Shot 2022-02-24 at 2 15 16 PM

I am testing your branch on my local install right now and will let you know what I find. Maybe you can check my profile page on your installation and let me know if you are seeing the same issue?

Thanks for the hard work!

**Comment by luukee** [comment]
@julia-elias Samuel C. Woolley is a team member that the metadata is not showing.

I think it has to do with your initial `if` statement on the `team-link.twig` file. Might have to rework it a bit.

Let me know what you figure out. Thanks!

**Comment by luukee** [comment]
@julia-elias My fields look similar to yours:
Screen Shot 2022-02-25 at 10 35 18 AM

But still no show :(
Screen Shot 2022-02-25 at 10 46 28 AM

Let me push it to the dev site & we'll see if it's just a bug on my machine. . .

**Pull request merged**
