### PR TITLE
Feature model fixes

### PR DESCRIPTION
**Pull request by Lay-ton**

### CODE REVIEW

**Comment by jeryj** [comment]
Can you give me some more context on this PR? 
- What issue does it solve?
- Why did you choose to solve it this way?
- How do you test to make sure it's working correctly?

**Comment by Lay-ton** [comment]
> Can you give me some more context on this PR?
> 
> * What issue does it solve?
> * Why did you choose to solve it this way?
> * How do you test to make sure it's working correctly?

This is for the following trello
https://trello.com/c/QL8MOOfw/54-extend-models-boardmemember-off-of-models-teammate-or-delete-models-boardmember
https://trello.com/c/rcmnMGTj/51-about-page-refactor
https://trello.com/c/gYM2caWW/57-remove-getresources-from-models-researcharticlephp-if-not-needed

Based on what the above trello cards say, I went ahead and carried out what they asked. They were mostly backend changes and refactoring. The best way to test was to make sure the pages they affected worked correctly.

**Comment by jeryj** [comment]
Thanks for the referencing trello cards. I think overall it looks good except for one change:
1. For the about page, I think we can remove the `Models\About` class entirely and just set a `$context['funders']` in `about.php` (not `About.php`).

A couple helpful notes for next time:
- keep PRs as isolated as possible. I could have merged the other work, but have to hold off due to the About template work.
- In general, this will usually mean one PR per trello card.
- When describing how to test it, specific links for the pages to check is helpful

Thanks for your work on this!

**Comment by Lay-ton** [comment]
> Thanks for the referencing trello cards. I think overall it looks good except for one change:
> 
> 1. For the about page, I think we can remove the `Models\About` class entirely and just set a `$context['funders']` in `about.php` (not `About.php`).
> 
> A couple helpful notes for next time:
> 
> * keep PRs as isolated as possible. I could have merged the other work, but have to hold off due to the About template work.
> * In general, this will usually mean one PR per trello card.
> * When describing how to test it, specific links for the pages to check is helpful
> 
> Thanks for your work on this!

I changed the context to context['funders'] in about.php, I'm pretty sure I have already deleted the model/About.php. I can't seem to find it in my local branch.

**Pull request merged**
